// Copyright © 2016-2022 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

//go:build ignore
// +build ignore

package sg

/*
#include <asm-generic/param.h>
#include </usr/include/scsi/sg.h>
*/
import "C"

const (
	SG_DXFER_NONE        = C.SG_DXFER_NONE
	SG_DXFER_TO_DEV      = C.SG_DXFER_TO_DEV
	SG_DXFER_FROM_DEV    = C.SG_DXFER_FROM_DEV
	SG_DXFER_TO_FROM_DEV = C.SG_DXFER_TO_FROM_DEV

	SG_FLAG_DIRECT_IO   = C.SG_FLAG_DIRECT_IO
	SG_FLAG_LUN_INHIBIT = C.SG_FLAG_LUN_INHIBIT

	SG_FLAG_NO_DXFER = C.SG_FLAG_NO_DXFER

	SG_INFO_OK_MASK = C.SG_INFO_OK_MASK
	SG_INFO_OK      = C.SG_INFO_OK
	SG_INFO_CHECK   = C.SG_INFO_CHECK

	SG_INFO_DIRECT_IO_MASK = C.SG_INFO_DIRECT_IO_MASK
	SG_INFO_INDIRECT_IO    = C.SG_INFO_INDIRECT_IO
	SG_INFO_DIRECT_IO      = C.SG_INFO_DIRECT_IO
	SG_INFO_MIXED_IO       = C.SG_INFO_MIXED_IO

	SG_EMULATED_HOST = C.SG_EMULATED_HOST

	SG_SET_TRANSFORM = C.SG_SET_TRANSFORM

	SG_GET_TRANSFORM = C.SG_GET_TRANSFORM

	SG_SET_RESERVED_SIZE = C.SG_SET_RESERVED_SIZE
	SG_GET_RESERVED_SIZE = C.SG_GET_RESERVED_SIZE

	SG_GET_SCSI_ID = C.SG_GET_SCSI_ID

	SG_SET_FORCE_LOW_DMA = C.SG_SET_FORCE_LOW_DMA
	SG_GET_LOW_DMA       = C.SG_GET_LOW_DMA

	SG_SET_FORCE_PACK_ID = C.SG_SET_FORCE_PACK_ID
	SG_GET_PACK_ID       = C.SG_GET_PACK_ID

	SG_GET_NUM_WAITING = C.SG_GET_NUM_WAITING

	SG_GET_SG_TABLESIZE = C.SG_GET_SG_TABLESIZE

	SG_GET_VERSION_NUM = C.SG_GET_VERSION_NUM

	SG_SCSI_RESET = C.SG_SCSI_RESET

	SG_SCSI_RESET_NOTHING = C.SG_SCSI_RESET_NOTHING
	SG_SCSI_RESET_DEVICE  = C.SG_SCSI_RESET_DEVICE
	SG_SCSI_RESET_BUS     = C.SG_SCSI_RESET_BUS
	SG_SCSI_RESET_HOST    = C.SG_SCSI_RESET_HOST

	SG_IO = C.SG_IO

	SG_GET_REQUEST_TABLE = C.SG_GET_REQUEST_TABLE

	SG_SET_KEEP_ORPHAN = C.SG_SET_KEEP_ORPHAN
	SG_GET_KEEP_ORPHAN = C.SG_GET_KEEP_ORPHAN

	SG_SCATTER_SZ = C.SG_SCATTER_SZ

	SG_DEFAULT_RETRIES = C.SG_DEFAULT_RETRIES

	SG_DEF_FORCE_LOW_DMA = C.SG_DEF_FORCE_LOW_DMA
	SG_DEF_FORCE_PACK_ID = C.SG_DEF_FORCE_PACK_ID
	SG_DEF_KEEP_ORPHAN   = C.SG_DEF_KEEP_ORPHAN
	SG_DEF_RESERVED_SIZE = C.SG_DEF_RESERVED_SIZE

	SG_MAX_QUEUE = C.SG_MAX_QUEUE

	SG_BIG_BUFF = C.SG_BIG_BUFF

	SG_MAX_SENSE = C.SG_MAX_SENSE

	SG_SET_TIMEOUT = C.SG_SET_TIMEOUT
	SG_GET_TIMEOUT = C.SG_GET_TIMEOUT

	SG_GET_COMMAND_Q = C.SG_GET_COMMAND_Q
	SG_SET_COMMAND_Q = C.SG_SET_COMMAND_Q

	SG_SET_DEBUG = C.SG_SET_DEBUG

	SG_NEXT_CMD_LEN = C.SG_NEXT_CMD_LEN

	SG_DEFAULT_TIMEOUT = C.SG_DEFAULT_TIMEOUT
	SG_DEF_COMMAND_Q   = C.SG_DEF_COMMAND_Q

	SG_DEF_UNDERRUN_FLAG = C.SG_DEF_UNDERRUN_FLAG
)

type SgIoVec C.struct_sg_iovec

type SgIoHdr C.struct_sg_io_hdr

type SgScsiId C.struct_sg_scsi_id

type SgReqInfo C.struct_sg_req_info

type SgHeader C.struct_sg_header
