// Copyright © 2016-2022 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

// +build ignore

package scsi

/*
#include <asm-generic/param.h>
#include </usr/include/scsi/scsi.h>
*/
import "C"

const (
	TEST_UNIT_READY       = C.TEST_UNIT_READY
	REZERO_UNIT           = C.REZERO_UNIT
	REQUEST_SENSE         = C.REQUEST_SENSE
	FORMAT_UNIT           = C.FORMAT_UNIT
	READ_BLOCK_LIMITS     = C.READ_BLOCK_LIMITS
	REASSIGN_BLOCKS       = C.REASSIGN_BLOCKS
	READ_6                = C.READ_6
	WRITE_6               = C.WRITE_6
	SEEK_6                = C.SEEK_6
	READ_REVERSE          = C.READ_REVERSE
	WRITE_FILEMARKS       = C.WRITE_FILEMARKS
	SPACE                 = C.SPACE
	INQUIRY               = C.INQUIRY
	RECOVER_BUFFERED_DATA = C.RECOVER_BUFFERED_DATA
	MODE_SELECT           = C.MODE_SELECT
	RESERVE               = C.RESERVE
	RELEASE               = C.RELEASE
	COPY                  = C.COPY
	ERASE                 = C.ERASE
	MODE_SENSE            = C.MODE_SENSE
	START_STOP            = C.START_STOP
	RECEIVE_DIAGNOSTIC    = C.RECEIVE_DIAGNOSTIC
	SEND_DIAGNOSTIC       = C.SEND_DIAGNOSTIC
	ALLOW_MEDIUM_REMOVAL  = C.ALLOW_MEDIUM_REMOVAL

	SET_WINDOW             = C.SET_WINDOW
	READ_CAPACITY          = C.READ_CAPACITY
	READ_10                = C.READ_10
	WRITE_10               = C.WRITE_10
	SEEK_10                = C.SEEK_10
	WRITE_VERIFY           = C.WRITE_VERIFY
	VERIFY                 = C.VERIFY
	SEARCH_HIGH            = C.SEARCH_HIGH
	SEARCH_EQUAL           = C.SEARCH_EQUAL
	SEARCH_LOW             = C.SEARCH_LOW
	SET_LIMITS             = C.SET_LIMITS
	PRE_FETCH              = C.PRE_FETCH
	READ_POSITION          = C.READ_POSITION
	SYNCHRONIZE_CACHE      = C.SYNCHRONIZE_CACHE
	LOCK_UNLOCK_CACHE      = C.LOCK_UNLOCK_CACHE
	READ_DEFECT_DATA       = C.READ_DEFECT_DATA
	MEDIUM_SCAN            = C.MEDIUM_SCAN
	COMPARE                = C.COMPARE
	COPY_VERIFY            = C.COPY_VERIFY
	WRITE_BUFFER           = C.WRITE_BUFFER
	READ_BUFFER            = C.READ_BUFFER
	UPDATE_BLOCK           = C.UPDATE_BLOCK
	READ_LONG              = C.READ_LONG
	WRITE_LONG             = C.WRITE_LONG
	CHANGE_DEFINITION      = C.CHANGE_DEFINITION
	WRITE_SAME             = C.WRITE_SAME
	READ_TOC               = C.READ_TOC
	LOG_SELECT             = C.LOG_SELECT
	LOG_SENSE              = C.LOG_SENSE
	MODE_SELECT_10         = C.MODE_SELECT_10
	RESERVE_10             = C.RESERVE_10
	RELEASE_10             = C.RELEASE_10
	MODE_SENSE_10          = C.MODE_SENSE_10
	PERSISTENT_RESERVE_IN  = C.PERSISTENT_RESERVE_IN
	PERSISTENT_RESERVE_OUT = C.PERSISTENT_RESERVE_OUT
	MOVE_MEDIUM            = C.MOVE_MEDIUM
	READ_12                = C.READ_12
	WRITE_12               = C.WRITE_12
	WRITE_VERIFY_12        = C.WRITE_VERIFY_12
	SEARCH_HIGH_12         = C.SEARCH_HIGH_12
	SEARCH_EQUAL_12        = C.SEARCH_EQUAL_12
	SEARCH_LOW_12          = C.SEARCH_LOW_12
	READ_ELEMENT_STATUS    = C.READ_ELEMENT_STATUS
	SEND_VOLUME_TAG        = C.SEND_VOLUME_TAG
	WRITE_LONG_2           = C.WRITE_LONG_2

	GOOD                 = C.GOOD
	CHECK_CONDITION      = C.CHECK_CONDITION
	CONDITION_GOOD       = C.CONDITION_GOOD
	BUSY                 = C.BUSY
	INTERMEDIATE_GOOD    = C.INTERMEDIATE_GOOD
	INTERMEDIATE_C_GOOD  = C.INTERMEDIATE_C_GOOD
	RESERVATION_CONFLICT = C.RESERVATION_CONFLICT
	COMMAND_TERMINATED   = C.COMMAND_TERMINATED
	QUEUE_FULL           = C.QUEUE_FULL

	STATUS_MASK = C.STATUS_MASK

	NO_SENSE        = C.NO_SENSE
	RECOVERED_ERROR = C.RECOVERED_ERROR
	NOT_READY       = C.NOT_READY
	MEDIUM_ERROR    = C.MEDIUM_ERROR
	HARDWARE_ERROR  = C.HARDWARE_ERROR
	ILLEGAL_REQUEST = C.ILLEGAL_REQUEST
	UNIT_ATTENTION  = C.UNIT_ATTENTION
	DATA_PROTECT    = C.DATA_PROTECT
	BLANK_CHECK     = C.BLANK_CHECK
	COPY_ABORTED    = C.COPY_ABORTED
	ABORTED_COMMAND = C.ABORTED_COMMAND
	VOLUME_OVERFLOW = C.VOLUME_OVERFLOW
	MISCOMPARE      = C.MISCOMPARE

	TYPE_DISK      = C.TYPE_DISK
	TYPE_TAPE      = C.TYPE_TAPE
	TYPE_PROCESSOR = C.TYPE_PROCESSOR
	TYPE_WORM      = C.TYPE_WORM
	TYPE_ROM       = C.TYPE_ROM
	TYPE_SCANNER   = C.TYPE_SCANNER
	TYPE_MOD       = C.TYPE_MOD

	TYPE_MEDIUM_CHANGER = C.TYPE_MEDIUM_CHANGER
	TYPE_ENCLOSURE      = C.TYPE_ENCLOSURE
	TYPE_NO_LUN         = C.TYPE_NO_LUN

	COMMAND_COMPLETE             = C.COMMAND_COMPLETE
	EXTENDED_MESSAGE             = C.EXTENDED_MESSAGE
	EXTENDED_MODIFY_DATA_POINTER = C.EXTENDED_MODIFY_DATA_POINTER
	EXTENDED_SDTR                = C.EXTENDED_SDTR
	EXTENDED_EXTENDED_IDENTIFY   = C.EXTENDED_EXTENDED_IDENTIFY
	EXTENDED_WDTR                = C.EXTENDED_WDTR
	SAVE_POINTERS                = C.SAVE_POINTERS
	RESTORE_POINTERS             = C.RESTORE_POINTERS
	DISCONNECT                   = C.DISCONNECT
	INITIATOR_ERROR              = C.INITIATOR_ERROR
	ABORT                        = C.ABORT
	MESSAGE_REJECT               = C.MESSAGE_REJECT
	NOP                          = C.NOP
	MSG_PARITY_ERROR             = C.MSG_PARITY_ERROR
	LINKED_CMD_COMPLETE          = C.LINKED_CMD_COMPLETE
	LINKED_FLG_CMD_COMPLETE      = C.LINKED_FLG_CMD_COMPLETE
	BUS_DEVICE_RESET             = C.BUS_DEVICE_RESET

	INITIATE_RECOVERY = C.INITIATE_RECOVERY
	RELEASE_RECOVERY  = C.RELEASE_RECOVERY

	SIMPLE_QUEUE_TAG  = C.SIMPLE_QUEUE_TAG
	HEAD_OF_QUEUE_TAG = C.HEAD_OF_QUEUE_TAG
	ORDERED_QUEUE_TAG = C.ORDERED_QUEUE_TAG

	SCSI_IOCTL_GET_IDLUN = C.SCSI_IOCTL_GET_IDLUN

	SCSI_IOCTL_TAGGED_ENABLE  = C.SCSI_IOCTL_TAGGED_ENABLE
	SCSI_IOCTL_TAGGED_DISABLE = C.SCSI_IOCTL_TAGGED_DISABLE

	SCSI_IOCTL_PROBE_HOST = C.SCSI_IOCTL_PROBE_HOST

	SCSI_IOCTL_GET_BUS_NUMBER = C.SCSI_IOCTL_GET_BUS_NUMBER
)

type CcsModeselHead C.struct_ccs_modesel_head
