// Code generated by scsi_id/godefs; DO NOT EDIT.

package scsi

const (
	TEST_UNIT_READY       = 0x0
	REZERO_UNIT           = 0x1
	REQUEST_SENSE         = 0x3
	FORMAT_UNIT           = 0x4
	READ_BLOCK_LIMITS     = 0x5
	REASSIGN_BLOCKS       = 0x7
	READ_6                = 0x8
	WRITE_6               = 0xa
	SEEK_6                = 0xb
	READ_REVERSE          = 0xf
	WRITE_FILEMARKS       = 0x10
	SPACE                 = 0x11
	INQUIRY               = 0x12
	RECOVER_BUFFERED_DATA = 0x14
	MODE_SELECT           = 0x15
	RESERVE               = 0x16
	RELEASE               = 0x17
	COPY                  = 0x18
	ERASE                 = 0x19
	MODE_SENSE            = 0x1a
	START_STOP            = 0x1b
	RECEIVE_DIAGNOSTIC    = 0x1c
	SEND_DIAGNOSTIC       = 0x1d
	ALLOW_MEDIUM_REMOVAL  = 0x1e

	SET_WINDOW             = 0x24
	READ_CAPACITY          = 0x25
	READ_10                = 0x28
	WRITE_10               = 0x2a
	SEEK_10                = 0x2b
	WRITE_VERIFY           = 0x2e
	VERIFY                 = 0x2f
	SEARCH_HIGH            = 0x30
	SEARCH_EQUAL           = 0x31
	SEARCH_LOW             = 0x32
	SET_LIMITS             = 0x33
	PRE_FETCH              = 0x34
	READ_POSITION          = 0x34
	SYNCHRONIZE_CACHE      = 0x35
	LOCK_UNLOCK_CACHE      = 0x36
	READ_DEFECT_DATA       = 0x37
	MEDIUM_SCAN            = 0x38
	COMPARE                = 0x39
	COPY_VERIFY            = 0x3a
	WRITE_BUFFER           = 0x3b
	READ_BUFFER            = 0x3c
	UPDATE_BLOCK           = 0x3d
	READ_LONG              = 0x3e
	WRITE_LONG             = 0x3f
	CHANGE_DEFINITION      = 0x40
	WRITE_SAME             = 0x41
	READ_TOC               = 0x43
	LOG_SELECT             = 0x4c
	LOG_SENSE              = 0x4d
	MODE_SELECT_10         = 0x55
	RESERVE_10             = 0x56
	RELEASE_10             = 0x57
	MODE_SENSE_10          = 0x5a
	PERSISTENT_RESERVE_IN  = 0x5e
	PERSISTENT_RESERVE_OUT = 0x5f
	MOVE_MEDIUM            = 0xa5
	READ_12                = 0xa8
	WRITE_12               = 0xaa
	WRITE_VERIFY_12        = 0xae
	SEARCH_HIGH_12         = 0xb0
	SEARCH_EQUAL_12        = 0xb1
	SEARCH_LOW_12          = 0xb2
	READ_ELEMENT_STATUS    = 0xb8
	SEND_VOLUME_TAG        = 0xb6
	WRITE_LONG_2           = 0xea

	GOOD                 = 0x0
	CHECK_CONDITION      = 0x1
	CONDITION_GOOD       = 0x2
	BUSY                 = 0x4
	INTERMEDIATE_GOOD    = 0x8
	INTERMEDIATE_C_GOOD  = 0xa
	RESERVATION_CONFLICT = 0xc
	COMMAND_TERMINATED   = 0x11
	QUEUE_FULL           = 0x14

	STATUS_MASK = 0x3e

	NO_SENSE        = 0x0
	RECOVERED_ERROR = 0x1
	NOT_READY       = 0x2
	MEDIUM_ERROR    = 0x3
	HARDWARE_ERROR  = 0x4
	ILLEGAL_REQUEST = 0x5
	UNIT_ATTENTION  = 0x6
	DATA_PROTECT    = 0x7
	BLANK_CHECK     = 0x8
	COPY_ABORTED    = 0xa
	ABORTED_COMMAND = 0xb
	VOLUME_OVERFLOW = 0xd
	MISCOMPARE      = 0xe

	TYPE_DISK      = 0x0
	TYPE_TAPE      = 0x1
	TYPE_PROCESSOR = 0x3
	TYPE_WORM      = 0x4
	TYPE_ROM       = 0x5
	TYPE_SCANNER   = 0x6
	TYPE_MOD       = 0x7

	TYPE_MEDIUM_CHANGER = 0x8
	TYPE_ENCLOSURE      = 0xd
	TYPE_NO_LUN         = 0x7f

	COMMAND_COMPLETE             = 0x0
	EXTENDED_MESSAGE             = 0x1
	EXTENDED_MODIFY_DATA_POINTER = 0x0
	EXTENDED_SDTR                = 0x1
	EXTENDED_EXTENDED_IDENTIFY   = 0x2
	EXTENDED_WDTR                = 0x3
	SAVE_POINTERS                = 0x2
	RESTORE_POINTERS             = 0x3
	DISCONNECT                   = 0x4
	INITIATOR_ERROR              = 0x5
	ABORT                        = 0x6
	MESSAGE_REJECT               = 0x7
	NOP                          = 0x8
	MSG_PARITY_ERROR             = 0x9
	LINKED_CMD_COMPLETE          = 0xa
	LINKED_FLG_CMD_COMPLETE      = 0xb
	BUS_DEVICE_RESET             = 0xc

	INITIATE_RECOVERY = 0xf
	RELEASE_RECOVERY  = 0x10

	SIMPLE_QUEUE_TAG  = 0x20
	HEAD_OF_QUEUE_TAG = 0x21
	ORDERED_QUEUE_TAG = 0x22

	SCSI_IOCTL_GET_IDLUN = 0x5382

	SCSI_IOCTL_TAGGED_ENABLE  = 0x5383
	SCSI_IOCTL_TAGGED_DISABLE = 0x5384

	SCSI_IOCTL_PROBE_HOST = 0x5385

	SCSI_IOCTL_GET_BUS_NUMBER = 0x5386
)

type CcsModeselHead struct {
	XR1             uint8
	Medium          uint8
	XR2             uint8
	BlockDescLength uint8
	Density         uint8
	NumberBlocksHi  uint8
	NumberBlocksMed uint8
	NumberBlocksLo  uint8
	XR3             uint8
	BlockLengthHi   uint8
	BlockLengthMed  uint8
	BlockLengthLo   uint8
}
